// form1/src/client/home.tsx
import React, { useState, useEffect } from 'react';
import { z } from 'zod';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Checkbox } from "@/components/ui/checkbox";

const TodoSchema = z.object({
  title: z.string().min(1, "タイトルは必須です"),
  content: z.string().min(1, "内容は必須です"),
  public: z.boolean(),
  foodOrange: z.boolean(),
  foodApple: z.boolean(),
  foodBanana: z.boolean(),
  pubDate: z.string(),
  qty1: z.string().min(1, "数量1は必須です"),
  qty2: z.string().min(1, "数量2は必須です"),
  qty3: z.string().min(1, "数量3は必須です"),
});

const TodoApp = () => {
  const [todos, setTodos] = useState([]);
  const [isOpen, setIsOpen] = useState(false);
  const [editingTodo, setEditingTodo] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [errors, setErrors] = useState({});
  const [formData, setFormData] = useState({
    title: '',
    content: '',
    public: false,
    foodOrange: false,
    foodApple: false,
    foodBanana: false,
    pubDate: '',
    qty1: '',
    qty2: '',
    qty3: '',
  });

  useEffect(() => {
    fetchTodos();
  }, [searchQuery]);

  const fetchTodos = async () => {
    try {
      const response = await fetch(`/api/todos${searchQuery ? `?search=${searchQuery}` : ''}`);
      const data = await response.json();
      //console.log( data );
      setTodos(data);
    } catch (error) {
      console.error('Error fetching todos:', error);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setErrors({});

    try {
      TodoSchema.parse(formData);

      const response = await fetch(
        `/api/todos${editingTodo ? `/${editingTodo.id}` : ''}`,
        {
          method: editingTodo ? 'PUT' : 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(formData),
        }
      );

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.message);
      }

      await fetchTodos();
      setIsOpen(false);
      resetForm();
    } catch (error) {
      if (error instanceof z.ZodError) {
        const errorMessages = {};
        error.errors.forEach((err) => {
          errorMessages[err.path[0]] = err.message;
        });
        setErrors(errorMessages);
      }
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('本当に削除しますか？')) {
      try {
        await fetch(`/api/todos/${id}`, {
          method: 'DELETE',
        });
        await fetchTodos();
      } catch (error) {
        console.error('Error deleting todo:', error);
      }
    }
  };

  const handleEdit = (todo) => {
    setEditingTodo(todo);
    setFormData({
      title: todo.title,
      content: todo.content,
      public: todo.public,
      foodOrange: todo.foodOrange,
      foodApple: todo.foodApple,
      foodBanana: todo.foodBanana,
      pubDate: new Date(todo.pubDate).toISOString().split('T')[0],
      qty1: todo.qty1,
      qty2: todo.qty2,
      qty3: todo.qty3,
    });
    setIsOpen(true);
  };

  const resetForm = () => {
    setFormData({
      title: '',
      content: '',
      public: false,
      foodOrange: false,
      foodApple: false,
      foodBanana: false,
      pubDate: '',
      qty1: '0',
      qty2: '0',
      qty3: '0',
    });
    setEditingTodo(null);
  };

  return (
    <div className="container mx-auto p-4">
      <div className="mb-4">
        <Input
          type="text"
          placeholder="検索..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full max-w-xs"
        />
      </div>

      <Dialog open={isOpen} onOpenChange={setIsOpen}>
        <DialogTrigger asChild>
          <Button onClick={resetForm}>新規作成</Button>
        </DialogTrigger>
        <DialogContent className="sm:max-w-[500px] max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{editingTodo ? 'TODOを編集' : '新規TODO作成'}</DialogTitle>
          </DialogHeader>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <Label htmlFor="title">タイトル</Label>
              <Input
                id="title"
                value={formData.title}
                onChange={(e) => setFormData({ ...formData, title: e.target.value })}
              />
              {errors.title && <p className="text-red-500 text-sm">{errors.title}</p>}
            </div>

            <div>
              <Label htmlFor="content">内容</Label>
              <Input
                id="content"
                value={formData.content}
                onChange={(e) => setFormData({ ...formData, content: e.target.value })}
              />
              {errors.content && <p className="text-red-500 text-sm">{errors.content}</p>}
            </div>

            <div>
              <Label>公開設定</Label>
              <RadioGroup
                value={formData.public.toString()}
                onValueChange={(value) => setFormData({ ...formData, public: value === 'true' })}
              >
                <div className="flex items-center space-x-2">
                  <RadioGroupItem value="true" id="public" />
                  <Label htmlFor="public">公開</Label>
                </div>
                <div className="flex items-center space-x-2">
                  <RadioGroupItem value="false" id="private" />
                  <Label htmlFor="private">非公開</Label>
                </div>
              </RadioGroup>
            </div>

            <div className="space-y-2">
              <Label>食べ物</Label>
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="foodOrange"
                  checked={formData.foodOrange}
                  onCheckedChange={(checked) => setFormData({ ...formData, foodOrange: checked })}
                />
                <Label htmlFor="foodOrange">オレンジ</Label>
              </div>
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="foodApple"
                  checked={formData.foodApple}
                  onCheckedChange={(checked) => setFormData({ ...formData, foodApple: checked })}
                />
                <Label htmlFor="foodApple">りんご</Label>
              </div>
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="foodBanana"
                  checked={formData.foodBanana}
                  onCheckedChange={(checked) => setFormData({ ...formData, foodBanana: checked })}
                />
                <Label htmlFor="foodBanana">バナナ</Label>
              </div>
            </div>

            <div>
              <Label htmlFor="pubDate">公開日</Label>
              <Input
                type="date"
                id="pubDate"
                value={formData.pubDate}
                onChange={(e) => setFormData({ ...formData, pubDate: e.target.value })}
              />
            </div>

            <div>
              <Label htmlFor="qty1">数量1</Label>
              <Input
                id="qty1"
                value={formData.qty1}
                onChange={(e) => setFormData({ ...formData, qty1: e.target.value })}
              />
              {errors.qty1 && <p className="text-red-500 text-sm">{errors.qty1}</p>}
            </div>

            <div>
              <Label htmlFor="qty2">数量2</Label>
              <Input
                id="qty2"
                value={formData.qty2}
                onChange={(e) => setFormData({ ...formData, qty2: e.target.value })}
              />
              {errors.qty2 && <p className="text-red-500 text-sm">{errors.qty2}</p>}
            </div>

            <div>
              <Label htmlFor="qty3">数量3</Label>
              <Input
                id="qty3"
                value={formData.qty3}
                onChange={(e) => setFormData({ ...formData, qty3: e.target.value })}
              />
              {errors.qty3 && <p className="text-red-500 text-sm">{errors.qty3}</p>}
            </div>

            <Button type="submit">{editingTodo ? '更新' : '作成'}</Button>
          </form>
        </DialogContent>
      </Dialog>

      <div className="mt-4">
        {todos.map((todo) => (
          <div key={todo.id} className="border p-4 mb-2 rounded">
            <h3 className="font-bold">{todo.title}</h3>
            <p>{todo.content}</p>
            <div className="mt-2">
              <Button variant="outline" className="mr-2" onClick={() => handleEdit(todo)}>
                編集
              </Button>
              <Button variant="destructive" onClick={() => handleDelete(todo.id)}>
                削除
              </Button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default TodoApp;

// vue_todo2/src/client/Home.vue

// src/App.vue
<template>
  <div class="container mx-auto px-4 py-8">
    <h1 class="text-3xl font-bold mb-8">TODO アプリケーション</h1>
    
    <!-- 検索フォーム -->
    <div class="mb-6">
      <input
        type="text"
        v-model="searchQuery"
        @input="searchTodos"
        placeholder="タイトルで検索..."
        class="w-full p-2 border rounded"
      >
    </div>

    <!-- TODOリスト -->
    <div class="grid gap-4 mb-6">
      <div v-for="todo in todos" :key="todo.id" class="p-4 border rounded bg-white shadow">
        <div class="flex justify-between items-center">
          <h2 class="text-xl font-semibold">{{ todo.title }}</h2>
          <div>
            <button
              @click="openEditDialog(todo)"
              class="bg-blue-500 text-white px-3 py-1 rounded mr-2"
            >
              編集
            </button>
            <button
              @click="deleteTodo(todo.id)"
              class="bg-red-500 text-white px-3 py-1 rounded"
            >
              削除
            </button>
          </div>
        </div>
        <p class="mt-2">{{ todo.content }}</p>
        <div class="mt-2 grid grid-cols-2 gap-4">
          <div>
            <p>公開状態: {{ todo.public ? '公開' : '非公開' }}</p>
            <p>公開日: {{ todo.pub_date }}</p>
          </div>
          <div>
            <p>選択した食べ物:</p>
            <ul class="list-disc list-inside">
              <li v-if="todo.food_orange">オレンジ</li>
              <li v-if="todo.food_apple">りんご</li>
              <li v-if="todo.food_banana">バナナ</li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- 新規追加ボタン -->
    <button
      @click="openAddDialog"
      class="bg-green-500 text-white px-4 py-2 rounded fixed bottom-8 right-8"
    >
      新規追加
    </button>

    <!-- TODO追加/編集ダイアログ -->
    <div v-if="showDialog" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
      <div class="bg-white p-6 rounded-lg w-full max-w-2xl">
        <h2 class="text-2xl font-bold mb-4">
          {{ isEditing ? 'TODO編集' : '新規TODO追加' }}
        </h2>
        
        <form @submit.prevent="submitForm" class="space-y-4">
          <div>
            <label class="block mb-1">タイトル</label>
            <input
              type="text"
              v-model="formData.title"
              class="w-full p-2 border rounded"
              :class="{ 'border-red-500': errors.title }"
            >
            <p v-if="errors.title" class="text-red-500 text-sm mt-1">
              {{ errors.title }}
            </p>
          </div>

          <div>
            <label class="block mb-1">内容</label>
            <input
              type="text"
              v-model="formData.content"
              class="w-full p-2 border rounded"
              :class="{ 'border-red-500': errors.content }"
            >
            <p v-if="errors.content" class="text-red-500 text-sm mt-1">
              {{ errors.content }}
            </p>
          </div>

          <div>
            <label class="block mb-1">公開設定</label>
            <div class="space-x-4">
              <label>
                <input
                  type="radio"
                  v-model="formData.public"
                  :value="true"
                > 公開
              </label>
              <label>
                <input
                  type="radio"
                  v-model="formData.public"
                  :value="false"
                > 非公開
              </label>
            </div>
          </div>

          <div>
            <label class="block mb-1">好きな食べ物</label>
            <div class="space-x-4">
              <label>
                <input
                  type="checkbox"
                  v-model="formData.food_orange"
                > オレンジ
              </label>
              <label>
                <input
                  type="checkbox"
                  v-model="formData.food_apple"
                > りんご
              </label>
              <label>
                <input
                  type="checkbox"
                  v-model="formData.food_banana"
                > バナナ
              </label>
            </div>
          </div>

          <div>
            <label class="block mb-1">公開日</label>
            <input
              type="date"
              v-model="formData.pub_date"
              class="w-full p-2 border rounded"
            >
          </div>

          <div class="grid grid-cols-3 gap-4">
            <div>
              <label class="block mb-1">数量1</label>
              <input
                type="text"
                v-model="formData.qty1"
                class="w-full p-2 border rounded"
              >
            </div>
            <div>
              <label class="block mb-1">数量2</label>
              <input
                type="text"
                v-model="formData.qty2"
                class="w-full p-2 border rounded"
              >
            </div>
            <div>
              <label class="block mb-1">数量3</label>
              <input
                type="text"
                v-model="formData.qty3"
                class="w-full p-2 border rounded"
              >
            </div>
          </div>

          <div class="flex justify-end space-x-4 mt-6">
            <button
              type="button"
              @click="closeDialog"
              class="px-4 py-2 border rounded"
            >
              キャンセル
            </button>
            <button
              type="submit"
              class="px-4 py-2 bg-blue-500 text-white rounded"
            >
              {{ isEditing ? '更新' : '追加' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import axios from 'axios';
import { z } from 'zod';

// バリデーションスキーマの定義
const todoSchema = z.object({
  title: z.string().min(1, { message: 'タイトルは必須です' }),
  content: z.string().min(1, { message: '内容は必須です' }),
  public: z.boolean(),
  food_orange: z.boolean(),
  food_apple: z.boolean(),
  food_banana: z.boolean(),
  pub_date: z.string(),
  qty1: z.string(),
  qty2: z.string(),
  qty3: z.string(),
});

// APIのベースURL
//const API_BASE_URL = 'http://localhost:3000/api';
const API_BASE_URL = '/api';

// 状態管理
const todos = ref([]);
const showDialog = ref(false);
const isEditing = ref(false);
const currentTodoId = ref(null);
const searchQuery = ref('');
const errors = ref({});

// フォームデータの初期値
const initialFormData = {
  title: '',
  content: '',
  public: false,
  food_orange: false,
  food_apple: false,
  food_banana: false,
  pub_date: '',
  qty1: '',
  qty2: '',
  qty3: '',
};

const formData = ref({ ...initialFormData });

// TODO一覧の取得
const fetchTodos = async () => {
  try {
    const response = await axios.get(`${API_BASE_URL}/todos`);
    todos.value = response.data;
  } catch (error) {
    console.error('TODOの取得に失敗しました:', error);
  }
};

// 検索機能
const searchTodos = async () => {
  try {
    const response = await axios.get(`${API_BASE_URL}/todos`, {
      params: { search: searchQuery.value }
    });
    todos.value = response.data;
  } catch (error) {
    console.error('検索に失敗しました:', error);
  }
};

// フォーム送信時のバリデーション
const validateForm = () => {
  try {
    todoSchema.parse(formData.value);
    errors.value = {};
    return true;
  } catch (error) {
    errors.value = error.errors.reduce((acc, curr) => {
      acc[curr.path[0]] = curr.message;
      return acc;
    }, {});
    return false;
  }
};

// フォームの送信
const submitForm = async () => {
  if (!validateForm()) return;

  try {
    if (isEditing.value) {
      await axios.put(`${API_BASE_URL}/todos/${currentTodoId.value}`, formData.value);
    } else {
      await axios.post(`${API_BASE_URL}/todos`, formData.value);
    }
    await fetchTodos();
    closeDialog();
  } catch (error) {
    console.error('送信に失敗しました:', error);
  }
};

// TODOの削除
const deleteTodo = async (id) => {
  if (!confirm('本当に削除しますか？')) return;
  
  try {
    await axios.delete(`${API_BASE_URL}/todos/${id}`);
    await fetchTodos();
  } catch (error) {
    console.error('削除に失敗しました:', error);
  }
};

// ダイアログを開く（新規追加）
const openAddDialog = () => {
  isEditing.value = false;
  currentTodoId.value = null;
  formData.value = { ...initialFormData };
  showDialog.value = true;
};

// ダイアログを開く（編集）
const openEditDialog = (todo) => {
  isEditing.value = true;
  currentTodoId.value = todo.id;
  formData.value = { ...todo };
  showDialog.value = true;
};

// ダイアログを閉じる
const closeDialog = () => {
  showDialog.value = false;
  errors.value = {};
};

// 初期データの取得
onMounted(fetchTodos);
</script>
